name: CI/CD Pipline

on:
  push:
    branches:
      - 'feature/*'      
      - 'hotfix/*'
      - 'refactoring/*'
      - 'dev'
      - 'main'
#     paths:
#       - '**.py'
    
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  
env:
  MONGO_ADDRESS: ${{ secrets.MONGO_ADDRESS }}
  IAMPORT_KEY: ${{ secrets.IAMPORT_KEY }}
  IAMPORT_SECRET: ${{ secrets.IAMPORT_SECRET }}
  
  REMOTE_IP: ${{ secrets.REMOTE_IP }}
  REMOTE_SSH_ID: ${{ secrets.REMOTE_SSH_ID }}
  REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
  REMOTE_SSH_PORT: ${{ secrets.REMOTE_SSH_PORT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v3
    
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v3
#       with:
#         python-version: "3.10"
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
#     - name: Test with pytest
#       run: |
#         pytest -v
        
        
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: whoami
